-- =====================================================
-- MIGRATION: Import Magical Nepal Treks & Tours Data
-- Adds detailed itineraries, pricing, and content for
-- all treks, tours, and expeditions
-- =====================================================

-- 1. NEW TREKS (category = 'Trek')
INSERT INTO public.adventures (title, slug, description, long_description, image_url, duration, difficulty, price, category, sort_order, itinerary, includes, excludes, highlights)
SELECT * FROM (VALUES

-- GOSAIKUNDA LAKE TREK (Langtang)
('Gosaikunda Lake Trek','gosaikunda-lake-trek','A sacred alpine lake trek through Langtang National Park with stunning Himalayan views and rich Hindu-Buddhist mythology.','The Gosaikunda Lake trek is within Langtang National Park and takes in the high-altitude freshwater lake of Gosaikunda (4,380m). Gosaikunda is not only a Ramsar site (since 2007), meaning that it is a wetland of international importance, but it is also a site considered holy to Buddhists and Hindus. On this week-long trek, you will have dramatic views of the Manaslu range, Ganesh Himal range, Tibetan peaks, and Langtang Lirung, as well as the three lakes of Gosaikunda, Saraswati Kunda, and Bhairab Kunda. In Hindu mythology, Gosaikunda is the abode of the gods Shiva and Gauri. It is believed that Lord Shiva formed the lake when he thrust his holy trident into the mountain to extract water to drink. The waters are considered significant during the Janai Purnima festival at the full moon in August when thousands of pilgrims gather.','https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=1600','8 Days','Moderate','$850','Trek',20,
'[{"day":1,"title":"Kathmandu to Syabrubesi (Drive)","description":"7-8 hour scenic drive from Kathmandu to Syabrubesi (1,550m) through the Trisuli Valley. Overnight in teahouse."},{"day":2,"title":"Trek to Lama Hotel","description":"6-7 hour trek through lush bamboo and rhododendron forests alongside the Langtang River to Lama Hotel (2,380m)."},{"day":3,"title":"Lama Hotel to Thulo Syabru","description":"5-6 hour trek through dense forests with rhododendrons and oak trees, passing landslide areas and the charming village of Bamboo."},{"day":4,"title":"Thulo Syabru to Shin Gompa","description":"3-4 hour trek with steep ascent from Thulo Syabru (2,330m) through open landscapes to Shin Gompa (3,330m). Visit the local cheese factory."},{"day":5,"title":"Shin Gompa to Gosaikunda","description":"5-6 hour challenging ascent to Gosaikunda (4,460m). Cross Lauribina La Pass (4,610m). Reach the sacred glacial lakes."},{"day":6,"title":"Gosaikunda to Chandanbari","description":"6-7 hour mainly downhill trek retracing steps through Langtang Valley to Chandanbari (2,000m)."},{"day":7,"title":"Chandanbari to Dhunche","description":"8 hour descent through rhododendron and pine forests to Dhunche (1,300m)."},{"day":8,"title":"Dhunche to Kathmandu (Drive)","description":"6-8 hour drive back to Kathmandu (1,380m)."}]'::jsonb,
'["7 nights teahouse accommodation","Guide for 8 days","Kathmandu-Syabrubesi-Kathmandu local bus","Langtang National Park permit","8 breakfasts, 8 lunches, 7 dinners on trek"]'::jsonb,
'["Porter (optional USD 184)","Private Jeep (optional USD 260)","Hot/cold drinks","Travel insurance","Personal expenses","Tips"]'::jsonb,
'["Sacred Gosaikunda Lake — holy alpine lake revered by Hindus and Buddhists","Stunning views of Langtang, Ganesh Himal, and Manaslu ranges","Diverse landscapes from lush forests to glacial lakes","Rich Tamang and Sherpa culture","Cross Lauribina Pass (4,610m)","Janai Purnima festival pilgrimage in August"]'::jsonb),

-- TAMANG HERITAGE TREK (Langtang)
('Tamang Heritage Trek','tamang-heritage-trek','A cultural trek through traditional Tamang villages with stunning mountain views and authentic homestay experiences.','The Tamang Heritage Trek starts by driving from Kathmandu to Syafru Beshi and runs through the beautiful Langtang Valley with breathtaking views of Langtang and Ganesh Himal. Villages on the route are occupied by Tamang people, closely related to Tibetans, and so the culture is Buddhist with a good scattering of prayer wheels, chortens, prayer flags, and mani stones along the trails. The Tamang Heritage Trail lies in what was previously a restricted area near the Tibet border and was opened up to visitors lately. The people in this area have a culture, tradition, and religion that goes back hundreds of years, and the craftsmanship, dress, and stone-mud houses are testimony of this ancient background. For those interested in anthropology as well as trekking, this is the perfect trip.','https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=1600','11 Days','Moderate','$1,050','Trek',21,
'[{"day":1,"title":"Kathmandu to Syabrubesi (Drive)","description":"7-8 hour drive to Syabrubesi (1,460m). Overnight in teahouse."},{"day":2,"title":"Syabrubesi to Gatlang","description":"5 hour trek through yak pastures, lush forests, and rivers. Views of Ganesh Himal. Overnight Gatlang (2,238m)."},{"day":3,"title":"Gatlang to Tatopani","description":"6-7 hour trek descending through forests to Chilime, crossing Chilime Hydropower Dam. Overnight Tatopani (2,600m)."},{"day":4,"title":"Tatopani to Thuman","description":"5-6 hour trek through forests and cultivated land with mani walls. Traditional stone and wood Tamang architecture. Overnight Thuman (2,340m)."},{"day":5,"title":"Thuman to Briddim (via Lingling Pass)","description":"5-6 hour trek descending through forests, crossing Bhote Koshi River. Overnight Briddim (2,500m) with authentic homestay."},{"day":6,"title":"Briddim to Lama Hotel","description":"5-6 hour trek descending through forests with birdlife, crossing Ghopche Khola. Overnight Lama Hotel (2,480m)."},{"day":7,"title":"Lama Hotel to Langtang Village","description":"6-7 hour trek with 1,000m altitude gain. Pass Ghoretable. Views of Langtang range. Overnight Langtang Village (3,430m)."},{"day":8,"title":"Langtang Village to Kyanjin Gompa","description":"4 hour gradual climb upstream of Langtang River. Visit Kyanjin Gompa monastery. Overnight Kyanjin Gompa (3,870m)."},{"day":9,"title":"Kyanjin Gompa to Lama Hotel","description":"6 hour descent retracing steps through Mundu, Ghora Tabela. Overnight Lama Hotel."},{"day":10,"title":"Lama Hotel to Syabrubesi","description":"4 hour last hiking day along Langtang River. Overnight Syabrubesi."},{"day":11,"title":"Syabrubesi to Kathmandu (Drive)","description":"8-9 hour drive back to Kathmandu."}]'::jsonb,
'["10 nights teahouse accommodation","Guide for 11 days","Kathmandu-Syabrubesi-Kathmandu local bus","Langtang National Park permit","11 breakfasts, 10 lunches, 10 dinners on trek"]'::jsonb,
'["Porter (optional USD 230)","Private Jeep (optional USD 260)","Hotel in Kathmandu","Hot/cold drinks","Travel insurance","Personal expenses","Tips"]'::jsonb,
'["Rich Tamang culture and traditions","Traditional Tibetan-style houses and architecture","Views of Langtang, Ganesh Himal, and Tibetan peaks","Natural hot springs at Tatopani","Ancient monasteries and Buddhist prayer wheels","Authentic homestay in Briddim village"]'::jsonb),

-- HELAMBU TREK (Langtang)
('Helambu Trek','helambu-trek','A peaceful trek through Hyolmo villages and rhododendron forests, close to Kathmandu with stunning Himalayan views.','The Helambu Trek is a beautiful and accessible trek just north of Kathmandu, offering a perfect short adventure for those with limited time. The trail passes through picturesque Hyolmo (Sherpa) villages, lush rhododendron and pine forests, and offers stunning views of the Langtang range, Ganesh Himal, and Dorje Lakpa. Unlike the busier trekking routes, Helambu remains relatively quiet and offers an authentic cultural experience with the Hyolmo people, who share close ties with Tibetan Buddhism. The trek starts from Sundarijal at the edge of Kathmandu Valley and ends at Melamchi Bazaar.','https://images.pexels.com/photos/2901209/pexels-photo-2901209.jpeg?auto=compress&cs=tinysrgb&w=1600','6 Days','Moderate','$795','Trek',22,
'[{"day":1,"title":"Kathmandu to Sundarijal to Chisapani","description":"1 hour drive to Sundarijal. 4 hour trek to Chisapani (2,300m). Walk through Shivapuri National Park."},{"day":2,"title":"Chisapani to Kutumsang","description":"7 hour trek through forests and Hyolmo villages to Kutumsang (2,446m)."},{"day":3,"title":"Kutumsang to Thadepati","description":"6 hour trek to Thadepati (3,650m) — the highest point. Panoramic mountain views."},{"day":4,"title":"Thadepati to Tarke Ghyang","description":"6 hour trek descending to Tarke Ghyang (2,560m). Explore the ancient monastery."},{"day":5,"title":"Tarke Ghyang to Sermathang","description":"3-4 hour trek to Sermathang (2,610m). Beautiful Hyolmo village."},{"day":6,"title":"Sermathang to Melamchi Bazaar to Kathmandu","description":"3-4 hour trek to Melamchi. Drive back to Kathmandu."}]'::jsonb,
'["5 nights teahouse accommodation","Guide for 6 days","Kathmandu-Sundarijal & Melamchi-Kathmandu local bus","Shivapuri National Park Permit","6 breakfasts, 6 lunches, 5 dinners on trek"]'::jsonb,
'["Porter (optional USD 128)","Private Jeep (optional USD 196)","Hotel in Kathmandu","Hot/cold drinks","Travel insurance","Personal expenses","Tips"]'::jsonb,
'["Explore unique Hyolmo culture and traditional villages","Walk through lush rhododendron and pine forests","Stunning views of Langtang, Ganesh Himal, Dorje Lakpa","Ancient Buddhist monasteries and prayer wheels","Less crowded — peaceful trekking experience","Close to Kathmandu — minimal travel time"]'::jsonb),

-- ANNAPURNA BASE CAMP TREK (Annapurna)
('Annapurna Base Camp Trek','annapurna-base-camp','A spectacular trek into the heart of the Annapurna Sanctuary with 360-degree mountain views and Gurung hospitality.','The Annapurna Base Camp Trek is one of Nepal''s most beloved treks, taking you deep into the Annapurna Sanctuary — a natural amphitheater surrounded by towering peaks. At 4,130m, ABC offers a 360-degree panorama of Annapurna I (8,091m), Machhapuchhre (Fishtail), Hiunchuli, and Annapurna South. The journey passes through rhododendron forests, traditional Gurung villages, and alongside the Modi Khola River. You''ll experience two base camps — Annapurna Base Camp and Machhapuchhre Base Camp — making this an incredible value trek. The natural hot springs at Jhinu Danda provide the perfect end to the adventure.','https://images.pexels.com/photos/2356045/pexels-photo-2356045.jpeg?auto=compress&cs=tinysrgb&w=1600','10 Days','Moderate','$786','Trek',23,
'[{"day":1,"title":"Kathmandu to Pokhara to Ghandruk","description":"6-8 hour drive to Pokhara then 3 hour drive to Ghandruk (2,012m). Explore the beautiful Gurung village."},{"day":2,"title":"Ghandruk to Chomrong","description":"6 hour trek through terraced fields and forests with views of Machhapuchhre. Overnight Chomrong (2,170m)."},{"day":3,"title":"Chomrong to Bamboo","description":"4-5 hour trek descending to Chomrong Khola, then climbing through rhododendron and bamboo forests. Overnight Bamboo (2,310m)."},{"day":4,"title":"Bamboo to Deurali","description":"3-4 hour gentle climb through forests, passing Dovan and Himalaya. Overnight Deurali (3,230m)."},{"day":5,"title":"Deurali to Annapurna Base Camp","description":"5-6 hour trek passing Machhapuchhre Base Camp (3,700m). Enter the Annapurna Sanctuary. Reach ABC (4,130m)."},{"day":6,"title":"ABC to Bamboo","description":"6-7 hour descent retracing steps through the sanctuary. Overnight Bamboo."},{"day":7,"title":"Bamboo to Jhinu Danda","description":"5-6 hour trek with natural hot springs at Jhinu Danda (1,780m). Relax in the thermal pools beside the Modi Khola."},{"day":8,"title":"Jhinu Danda to Naya Pul to Pokhara","description":"5 hour final trek to Naya Pul. 1 hour drive to Pokhara. Celebration by Phewa Lake."},{"day":9,"title":"Pokhara to Kathmandu (Drive)","description":"7 hour drive back to Kathmandu."},{"day":10,"title":"Departure","description":"Airport transfer. End of service."}]'::jsonb,
'["7 nights teahouse accommodation","1 night Pokhara hotel","Guide for 9 days","Kathmandu-Pokhara-Kathmandu tourist bus","Pokhara-Naya Pul-Pokhara private car","ACAP permit + TIMS card","8 breakfasts, 8 lunches, 7 dinners on trek"]'::jsonb,
'["Porter (optional USD 249)","Lunch/dinner in Pokhara","Hotel in Kathmandu","Hot/cold drinks","Travel insurance","Tips"]'::jsonb,
'["360-degree mountain views at Annapurna Base Camp","Two base camps in one trek (ABC + Machhapuchhre BC)","Natural hot springs at Jhinu Danda","Gurung culture in Ghandruk village","Rhododendron forests in spring","Views of Machhapuchhre (Fishtail) mountain"]'::jsonb),

-- MARDI HIMAL BASE CAMP TREK (Annapurna)
('Mardi Himal Base Camp Trek','mardi-himal-base-camp','An off-the-beaten-path trek to the lap of Mardi Himal with stunning close-up views of Machhapuchhre.','The Mardi Himal Base Camp Trek is one of the Annapurna region''s best-kept secrets. This relatively new trekking route takes you through quiet forests, traditional villages, and alpine meadows to the base of Mardi Himal (4,450m). The trek offers incredibly close-up views of Machhapuchhre (Fishtail), Annapurna South, Hiunchuli, and the entire Annapurna massif. Unlike the busier ABC trek, Mardi Himal sees far fewer trekkers, offering a sense of solitude and pristine nature. The trail passes through rhododendron, pine, and oak forests, with the landscape transforming from lush green to stark alpine as you gain altitude.','https://images.pexels.com/photos/2901209/pexels-photo-2901209.jpeg?auto=compress&cs=tinysrgb&w=1600','7 Days','Moderate','$700','Trek',24,
'[{"day":1,"title":"Kathmandu to Pokhara","description":"8 hour drive or 25 minute flight to Pokhara (830m). Overnight in Pokhara."},{"day":2,"title":"Pokhara to Kande to Deurali","description":"1 hour drive to Kande. 5-6 hour trek to Deurali (2,200m)."},{"day":3,"title":"Deurali to Low Camp","description":"5-6 hour trek through rhododendron forests to Low Camp (2,900m)."},{"day":4,"title":"Low Camp to High Camp","description":"6-7 hour trek above the treeline with expanding mountain views. Overnight High Camp (3,585m)."},{"day":5,"title":"High Camp to Mardi Himal BC to Badal Danda","description":"Early start to Mardi Himal Base Camp (4,450m). Descend to Badal Danda (3,210m). 7-8 hours total."},{"day":6,"title":"Badal Danda to Sidhing to Pokhara","description":"5-6 hour trek to Sidhing. Drive back to Pokhara. Celebration evening."},{"day":7,"title":"Pokhara to Kathmandu","description":"5-7 hour drive back to Kathmandu."}]'::jsonb,
'["4 nights teahouse accommodation","1 night Pokhara hotel","Guide for 6 days","Kathmandu-Pokhara tourist bus","Pokhara-Phedi & Lwang-Pokhara private car","ACAP permit + TIMS card","6 breakfasts, 5 lunches, 5 dinners on trek"]'::jsonb,
'["Porter (optional USD 132)","Lunch/dinner in Pokhara","Hotel in Kathmandu","Hot/cold drinks","Travel insurance","Tips"]'::jsonb,
'["Off-the-beaten-path trail with fewer crowds","Close-up views of Machhapuchhre and Mardi Himal","Lush rhododendron, pine, and oak forests","Alpine meadows and pristine nature","Sense of solitude and wilderness","Stunning panoramic Himalayan views"]'::jsonb),

-- GOKYO LAKE TREK (Everest)
('Gokyo Lake Trek','gokyo-lake-trek','A stunning trek through the Everest region to the turquoise Gokyo Lakes with panoramic views from Gokyo Ri.','The Gokyo Lake Trek offers a quieter alternative to the Everest Base Camp trek with equally stunning scenery. The trek takes you to the beautiful turquoise Gokyo Lakes, a series of six glacial lakes designated as a Ramsar site. From the summit of Gokyo Ri (5,357m), you get one of the finest panoramic views in the entire Khumbu region — Everest, Lhotse, Makalu, and Cho Oyu all visible in a single sweeping vista. The trek also takes you alongside the Ngozumpa Glacier, the largest glacier in Nepal, and through traditional Sherpa villages like Namche Bazaar and Khumjung.','https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=1600','12 Days','Moderate','$1,250','Trek',25,
'[{"day":1,"title":"Arrive in Kathmandu","description":"Arrival and transfer to hotel. Trek briefing."},{"day":2,"title":"Fly to Lukla, Trek to Phakding","description":"Early flight to Lukla. 3-4 hour trek to Phakding (2,651m)."},{"day":3,"title":"Phakding to Namche Bazaar","description":"5-6 hour trek through pine forests and suspension bridges to Namche Bazaar (3,438m)."},{"day":4,"title":"Acclimatization in Namche","description":"Day hike to Khumjung village and Everest View Hotel. Acclimatization and exploration."},{"day":5,"title":"Namche to Dole","description":"6 hour trek through forests to Dole (3,680m)."},{"day":6,"title":"Dole to Machhermo","description":"5-6 hour trek to Machhermo (3,870m)."},{"day":7,"title":"Machhermo to Gokyo","description":"4 hour trek to Gokyo (4,800m). Afternoon hike to Gokyo Ri (5,357m) for sunset."},{"day":8,"title":"Explore Gokyo Lakes","description":"Morning hike to 4th and 5th Gokyo Lakes. Return to Machhermo (3,870m)."},{"day":9,"title":"Machhermo to Namche","description":"8 hour descent back to Namche Bazaar."},{"day":10,"title":"Namche to Lukla","description":"8 hour final trekking day back to Lukla."},{"day":11,"title":"Fly to Kathmandu","description":"Scenic flight back to Kathmandu."},{"day":12,"title":"Departure","description":"Airport transfer."}]'::jsonb,
'["Airport transfers","Kathmandu-Lukla-Kathmandu flights","2 nights Kathmandu hotel","10 nights teahouse accommodation","Guide for 11 days, Porter for 10 days","All permits (Sagarmatha NP + local)","11 breakfasts, 10 lunches, 10 dinners on trek"]'::jsonb,
'["Lunch and dinner in Kathmandu","Hot/cold drinks","Travel insurance","Personal expenses","Tips"]'::jsonb,
'["Turquoise Gokyo Lakes — a Ramsar site","Gokyo Ri (5,357m) — panoramic Everest views","Ngozumpa Glacier — largest glacier in Nepal","Sherpa culture in Namche and Khumjung","Fewer crowds than the EBC trek","Views of Everest, Lhotse, Makalu, and Cho Oyu"]'::jsonb),

-- 7 DAYS EVEREST BASE CAMP TREK WITH HELICOPTER RETURN
('7 Days Everest Base Camp Trek with Helicopter Return','everest-base-camp-helicopter-return','A shortened EBC trek with a spectacular helicopter return — see Everest in under a week.','This 7-day Everest Base Camp trek is designed for those with limited time who still want to experience the magic of the Khumbu. You''ll trek through the classic route to Tengboche, experiencing the Sherpa culture, suspension bridges, and stunning mountain scenery. Then, instead of trekking back, you''ll board a helicopter from Tengboche that flies over Everest Base Camp and lands at Kala Patthar (5,545m) for the iconic Everest photo, before flying you directly back to Kathmandu. This is the most efficient way to experience the world''s highest mountain.','https://images.pexels.com/photos/933054/pexels-photo-933054.jpeg?auto=compress&cs=tinysrgb&w=1600','7 Days','Strenuous','$2,499','Trek',26,
'[{"day":1,"title":"Welcome to Kathmandu","description":"Arrival and hotel transfer. Pre-trek briefing."},{"day":2,"title":"Fly to Lukla, Trek to Phakding","description":"Early flight to Lukla. 3-4 hour trek to Phakding (2,651m)."},{"day":3,"title":"Phakding to Namche Bazaar","description":"5-6 hour trek crossing 5 suspension bridges to Namche Bazaar (3,440m)."},{"day":4,"title":"Acclimatization in Namche","description":"Day hike to Khumjung village and Everest View Hotel."},{"day":5,"title":"Namche to Tengboche","description":"5-6 hour trek to Tengboche (3,956m). Visit the famous monastery."},{"day":6,"title":"Helicopter: Tengboche to EBC to Kala Patthar to Kathmandu","description":"Helicopter flight from Tengboche over Everest Base Camp with landing at Kala Patthar (5,545m). Fly back to Kathmandu."},{"day":7,"title":"Final Departure","description":"Airport transfer. End of service."}]'::jsonb,
'["Airport transfers","Kathmandu-Lukla flight","Helicopter Tengboche-EBC-Kala Patthar-Kathmandu","5 nights teahouse accommodation","2 nights Kathmandu hotel","Guide for 7 days, Porter for 6 days","All permits","7 breakfasts, 6 lunches, 6 dinners on trek"]'::jsonb,
'["Lunch/dinner in Kathmandu","Hot/cold drinks","Travel insurance","Personal expenses","Tips","WiFi card (USD 25)"]'::jsonb,
'["Fly to Lukla — world''s most thrilling airport","Helicopter return — no long hike back","Sherpa culture in Namche Bazaar","Tengboche Monastery","Kala Patthar (5,545m) — best Everest views","Complete experience in just 7 days"]'::jsonb),

-- TSUM VALLEY TREK (Manaslu)
('Tsum Valley Trek','tsum-valley-trek','A sacred hidden valley of Tibetan Buddhism, remote monasteries, and stunning Himalayan landscapes.','The Tsum Valley Trek takes you into one of Nepal''s most spiritually significant regions. Not opened to trekkers until 2008, this remote valley is known as the "Hidden Valley" and is rich in Tibetan Buddhist culture. The trail passes through ancient monasteries including Mu Gompa and Rachen Gompa, visits Milarepa''s meditation cave, and offers stunning views of Mt. Manaslu (8,163m), the 8th highest mountain in the world. The Tsum people are of Tibetan origin, and the valley is dotted with chortens, mani walls, and prayer flags.','https://images.pexels.com/photos/1183099/pexels-photo-1183099.jpeg?auto=compress&cs=tinysrgb&w=1600','11 Days','Moderate','$1,100','Trek',27,
'[{"day":1,"title":"Drive Kathmandu to Machha Khola","description":"9 hour drive from Kathmandu to Machha Khola (930m)."},{"day":2,"title":"Machha Khola to Jagat","description":"6-7 hour trek through forests and along the Budhi Gandaki River."},{"day":3,"title":"Jagat to Lokpa","description":"5-6 hour trek entering the Manaslu Conservation Area."},{"day":4,"title":"Lokpa to Chumling","description":"5 hour trek entering the Tsum Valley. Traditional Tibetan villages."},{"day":5,"title":"Chumling to Chekampar","description":"3-4 hour trek with views of Ganesh Himal."},{"day":6,"title":"Chekampar to Nile","description":"3-4 hour trek passing ancient monasteries."},{"day":7,"title":"Day trip to Mu Gompa","description":"7 hour round trip hike to Mu Gompa (3,700m) — the highest monastery in the valley."},{"day":8,"title":"Return to Chumling","description":"5-6 hour descent back through the valley."},{"day":9,"title":"Chumling to Philim","description":"6-7 hour trek descending through forests."},{"day":10,"title":"Philim to Machha Khola","description":"6-7 hour trek back to the trailhead."},{"day":11,"title":"Drive to Kathmandu","description":"8 hour drive back to Kathmandu."}]'::jsonb,
'["Airport transfers","10 nights teahouse accommodation","Guide for 11 days","Kathmandu-Machha Khola-Kathmandu local bus","All necessary permits","11 breakfasts, 11 lunches, 11 dinners on trek"]'::jsonb,
'["Hotel in Kathmandu","Porter (optional USD 299)","Private Jeep (optional USD 320)","Hot/cold drinks","Travel insurance","Personal expenses","Tips"]'::jsonb,
'["Not open until 2008 — very remote and untouched","Visit Mu Gompa and Rachen Gompa monasteries","Milarepa''s meditation cave","Tibetan-border culture and people","Views of Mt. Manaslu (8th highest in world)","High suspension and cantilever bridges"]'::jsonb),

-- KHOPRA RIDGE TREK (Annapurna)
('Khopra Ridge Trek','khopra-ridge-trek','A hidden gem above the Annapurna region with breathtaking views from Khopra Danda and the Muldai viewpoint.','The Khopra Ridge Trek is one of the Annapurna region''s best-kept secrets. Also known as the "Khopra Danda Trek," this route takes you away from the crowded trails to a stunning ridge at 3,660m with unobstructed views of the Annapurna and Dhaulagiri ranges. The highlight is the hike to Muldai Viewpoint (3,900m) for sunrise over Dhaulagiri, Annapurna South, and Machhapuchhre. The trail passes through traditional villages, rhododendron forests, and offers a genuine off-the-beaten-path experience.','https://images.pexels.com/photos/2901209/pexels-photo-2901209.jpeg?auto=compress&cs=tinysrgb&w=1600','9 Days','Moderate','$780','Trek',28,
'[{"day":1,"title":"Kathmandu to Pokhara","description":"6-7 hour drive or 25 minute flight to Pokhara."},{"day":2,"title":"Pokhara to Ghandruk","description":"Drive to Ghandruk (2,012m). Explore the Gurung village."},{"day":3,"title":"Ghandruk to Tadapani","description":"5-6 hour trek through rhododendron forests to Tadapani (2,630m)."},{"day":4,"title":"Tadapani to Khopra Ridge","description":"6 hour trek through forests and pastures to Khopra Ridge (3,660m)."},{"day":5,"title":"Muldai Viewpoint Hike","description":"Early morning hike to Muldai Viewpoint (3,900m) for sunrise. Return to Khopra."},{"day":6,"title":"Khopra to Swanta","description":"5 hour descent to Swanta village."},{"day":7,"title":"Swanta to Ghorepani","description":"5 hour trek through forests to Ghorepani."},{"day":8,"title":"Poon Hill Sunrise & Trek to Nayapul","description":"Early hike to Poon Hill. Descend to Nayapul. Drive to Pokhara."},{"day":9,"title":"Pokhara to Kathmandu","description":"Drive back to Kathmandu."}]'::jsonb,
'["7 nights teahouse accommodation","1 night Pokhara hotel","Guide for 9 days","Kathmandu-Pokhara-Kathmandu tourist bus","Private car to trailhead and return","ACAP permit + TIMS card","All meals on trek"]'::jsonb,
'["Porter (optional)","Lunch/dinner in Pokhara","Hotel in Kathmandu","Hot/cold drinks","Travel insurance","Tips"]'::jsonb,
'["Muldai Viewpoint — sunrise over Dhaulagiri and Annapurna","Less crowded — true off-the-beaten-path","Panoramic Himalayan views from Khopra Ridge","Traditional Gurung villages","Rhododendron forests and alpine meadows","Combine with Poon Hill sunrise"]'::jsonb),

-- KANCHENJUNGA CIRCUIT TREK (Kanchenjunga)
('Kanchenjunga Circuit Trek','kanchenjunga-circuit-trek','An epic journey around the world''s 3rd highest mountain through remote wilderness and pristine landscapes.','The Kanchenjunga Circuit Trek is one of Nepal''s most remote and challenging treks. Circling Mt. Kanchenjunga (8,586m), the world''s 3rd highest mountain, this trek takes you through pristine wilderness, remote villages, and high alpine passes. The trail passes through the Kanchenjunga Conservation Area, home to diverse wildlife including snow leopards, Himalayan black bears, and red pandas. You''ll visit both the North and South Base Camps, cross the Sele Le Pass (4,320m), and experience the unique cultures of the Limbu, Rai, and Tibetan communities. This is a trek for those seeking true adventure and solitude.','https://images.pexels.com/photos/2387418/pexels-photo-2387418.jpeg?auto=compress&cs=tinysrgb&w=1600','19 Days','Challenging','$2,200','Trek',29,
'[{"day":1,"title":"Arrive in Kathmandu","description":"Arrival and hotel transfer."},{"day":2,"title":"Fly to Bhadrapur, Drive to Phidim","description":"Flight to Bhadrapur. Scenic drive to Phidim."},{"day":3,"title":"Phidim to Kande Bhanjyang","description":"Begin trekking through rice terraces and subtropical forests."},{"day":4,"title":"Kande Bhanjyang to Mamankhe","description":"Trek through Limbu and Rai villages."},{"day":5,"title":"Mamankhe to Yamphudin","description":"Enter the Kanchenjunga Conservation Area."},{"day":6,"title":"Yamphudin to Tortong","description":"Trek through dense forests with views of Kanchenjunga."},{"day":7,"title":"Tortong to Tseram","description":"Enter alpine terrain with expanding Himalayan views."},{"day":8,"title":"Tseram to Kanchenjunga South BC","description":"Visit Kanchenjunga South Base Camp (4,800m)."},{"day":9,"title":"Return to Tseram","description":"Descend back to Tseram."},{"day":10,"title":"Tseram to Ghunsa","description":"Trek through beautiful valleys to Ghunsa village."},{"day":11,"title":"Ghunsa to Khambachen","description":"Ascend through alpine meadows to Khambachen (4,050m)."},{"day":12,"title":"Khambachen to Lhonak","description":"Trek through glacial terrain to Lhonak (4,790m)."},{"day":13,"title":"Kanchenjunga North BC","description":"Day hike to Kanchenjunga North Base Camp (5,143m)."},{"day":14,"title":"Cross Sele Le Pass","description":"Cross the high Sele Le Pass (4,320m). Descend to camp."},{"day":15,"title":"Trek to Ghunsa","description":"Descend through beautiful valleys."},{"day":16,"title":"Trek to Phidim","description":"Continue descent through forests and villages."},{"day":17,"title":"Drive to Bhadrapur","description":"Scenic drive back to Bhadrapur."},{"day":18,"title":"Fly to Kathmandu","description":"Flight back to Kathmandu."},{"day":19,"title":"Departure","description":"Airport transfer."}]'::jsonb,
'["Airport transfers","Domestic flights (Kathmandu-Bhadrapur)","Hotel in Kathmandu","Teahouse/camping accommodation","All meals on trek","English-speaking guide","Porter service","Kanchenjunga Conservation Area permit","Restricted Area permit","TIMS card"]'::jsonb,
'["International flights","Nepal visa","Travel insurance","Personal gear","Hot showers","Tips","Alcoholic drinks"]'::jsonb,
'["Trek around the world''s 3rd highest mountain (8,586m)","Visit both North and South Base Camps","Cross Sele Le Pass (4,320m)","Remote wilderness — very few trekkers","Unique Limbu, Rai, and Tibetan cultures","Wildlife: snow leopards, red pandas, black bears"]'::jsonb),

-- UPPER DOLPO CIRCUIT TREK (Dolpo)
('Upper Dolpo Circuit Trek','upper-dolpo-circuit-trek','A legendary journey through ancient Buddhist landscapes, turquoise lakes, and the hidden valleys of Dolpo.','The Upper Dolpo Circuit Trek is one of the most remote and awe-inspiring treks in Nepal. Located in the far northwestern region, Dolpo is a land of ancient Tibetan Buddhist culture, arid trans-Himalayan landscapes, and stunning turquoise lakes. The trek crosses several high passes over 5,000m, including the Numa La (5,190m) and Baga La (5,070m), and visits the pristine Phoksundo Lake (3,611m) — Nepal''s deepest lake. Dolpo gained fame through Peter Matthiessen''s book "The Snow Leopard" and remains one of the most culturally and geographically unique regions of Nepal. This is a true wilderness expedition requiring camping.','https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg?auto=compress&cs=tinysrgb&w=1600','24 Days','Challenging','$3,200','Trek',30,
'[{"day":1,"title":"Arrive in Kathmandu","description":"Arrival and expedition briefing."},{"day":2,"title":"Fly to Nepalgunj","description":"Domestic flight to Nepalgunj."},{"day":3,"title":"Fly to Juphal, Trek to Chhepka","description":"Flight to Juphal. Begin trekking through pine forests."},{"day":4,"title":"Chhepka to Phoksundo Lake","description":"Trek to the stunning turquoise Phoksundo Lake (3,611m)."},{"day":5,"title":"Explore Phoksundo","description":"Day hike to the Ringmo village and Phoksundo waterfall."},{"day":6,"title":"Phoksundo to Thasher Manla","description":"Begin crossing the first high passes."},{"day":7,"title":"Cross Numa La Pass","description":"Cross Numa La (5,190m). Camp on the far side."},{"day":8,"title":"Cross Baga La Pass","description":"Cross Baga La (5,070m). Descend to the Shey Valley."},{"day":9,"title":"Shey Gompa","description":"Visit the ancient Shey Gompa monastery."},{"day":10,"title":"Shey Gompa to Namdune","description":"Trek through the pristine Shey Valley."},{"day":11,"title":"Namdune to Saldang","description":"Enter the main Dolpo settlement area."},{"day":12,"title":"Explore Saldang","description":"Rest day exploring the largest village in Dolpo."},{"day":13,"title":"Saldang to Yangtse Gompa","description":"Visit the remote Yangtse Gompa."},{"day":14,"title":"Yangtse to Sibu","description":"Continue through the trans-Himalayan landscape."},{"day":15,"title":"Sibu to Jeng La Phedi","description":"Approach the Jeng La Pass."},{"day":16,"title":"Cross Jeng La Pass","description":"Cross Jeng La (5,110m). Descend to Tokyu."},{"day":17,"title":"Tokyu to Taling","description":"Descend through juniper forests."},{"day":18,"title":"Taling to Dunai","description":"Return to the main trailhead."},{"day":19,"title":"Dunai to Juphal","description":"Final day of trekking."},{"day":20,"title":"Fly to Kathmandu","description":"Flight via Nepalgunj to Kathmandu."}]'::jsonb,
'["All domestic flights","All camping equipment (tents, mattresses, kitchen)","Full board meals on trek","English-speaking guide","Cook and kitchen staff","Camping permits and National Park fees","TIMS card","Satellite phone","Emergency first aid kit"]'::jsonb,
'["International flights","Nepal visa","Travel insurance","Personal clothing and sleeping bag","Tips","Alcoholic drinks","Hot showers (not available)"]'::jsonb,
'["Phoksundo Lake — Nepal''s deepest and most beautiful lake","Cross three high passes over 5,000m","Ancient Tibetan Buddhist monasteries","Remote wilderness — see The Snow Leopard country","Unique Dolpo-pa culture","Camping expedition — true adventure"]'::jsonb),

-- MAKALU BASE CAMP TREK (Makalu)
('Makalu Base Camp Trek','makalu-base-camp-trek','A remote wilderness trek to the base of the world''s 5th highest mountain through pristine forests and alpine meadows.','The Makalu Base Camp Trek is one of Nepal''s most challenging and rewarding treks. The trail leads to the base of Mt. Makalu (8,463m), the world''s 5th highest mountain, through some of the most pristine and biodiverse forests in Nepal. The trek passes through the Makalu-Barun National Park, which features a spectacular altitude gradient from subtropical forests at 400m to alpine terrain above 5,000m. The region is home to over 3,000 species of flowering plants, 440 species of birds, and 75 species of mammals including the elusive snow leopard. The trek crosses the Shipton La Pass (4,217m) and offers incredible views of Makalu, Everest, Lhotse, and Chamlang.','https://images.pexels.com/photos/2387418/pexels-photo-2387418.jpeg?auto=compress&cs=tinysrgb&w=1600','19 Days','Challenging','$2,100','Trek',31,
'[{"day":1,"title":"Arrive in Kathmandu","description":"Arrival and expedition briefing."},{"day":2,"title":"Fly to Tumlingtar","description":"Scenic flight to Tumlingtar. Prepare for trek."},{"day":3,"title":"Trek to Num","description":"Begin trekking through subtropical forests and rice terraces."},{"day":4,"title":"Num to Seduwa","description":"Ascend through the Arun Valley."},{"day":5,"title":"Seduwa to Tashigaon","description":"Enter Makalu-Barun National Park."},{"day":6,"title":"Tashigaon to Khongma","description":"Trek through rhododendron and bamboo forests."},{"day":7,"title":"Khongma to Mumbuk","description":"Enter alpine terrain above the treeline."},{"day":8,"title":"Mumbuk to Nehe Kharka","description":"Cross the Shipton La Pass (4,217m)."},{"day":9,"title":"Nehe Kharka to Base Camp","description":"Arrive at Makalu Base Camp (4,870m)."},{"day":10,"title":"Explore Makalu BC","description":"Day exploring the base camp area. Views of Makalu."},{"day":11,"title":"Begin descent","description":"Start the return journey."},{"day":12,"title":"Retrace to Khongma","description":"Descend through alpine terrain."},{"day":13,"title":"Khongma to Tashigaon","description":"Continue descending through forests."},{"day":14,"title":"Tashigaon to Num","description":"Return through the Arun Valley."},{"day":15,"title":"Num to Tumlingtar","description":"Final day of trekking."},{"day":16,"title":"Fly to Kathmandu","description":"Return flight."}]'::jsonb,
'["Airport transfers","Domestic flights","Hotel in Kathmandu","Teahouse/camping accommodation","All meals on trek","English-speaking guide","Porter service","Makalu-Barun National Park permit","TIMS card","Satellite phone"]'::jsonb,
'["International flights","Nepal visa","Travel insurance","Personal gear","Tips","Alcoholic drinks"]'::jsonb,
'["Trek to the base of the world''s 5th highest mountain (8,463m)","Cross Shipton La Pass (4,217m)","Makalu-Barun National Park — incredible biodiversity","Remote wilderness — very few trekkers","Views of Makalu, Everest, Lhotse, and Chamlang","Spectacular altitude gradient from 400m to 5,000m+"]'::jsonb),

-- UPPER MUSTANG TREK (already exists as seed, adding detailed version)
-- This is covered by the existing seed, skipping

-- DHAULAGIRI CIRCUIT TREK
('Dhaulagiri Circuit Trek','dhaulagiri-circuit-trek','A challenging camping trek around the world''s 7th highest mountain through dramatic glacier terrain.','The Dhaulagiri Circuit Trek is a true wilderness expedition that circles Mt. Dhaulagiri (8,167m), the world''s 7th highest mountain. This is a camping-only trek that crosses two high passes — the French Pass (5,360m) and the Dhampus Pass (5,246m) — and traverses the massive Dhaulagiri Glacier. The trek offers some of the most dramatic mountain scenery in Nepal, with close-up views of Dhaulagiri''s towering ice walls, the famous "Hidden Valley," and panoramic views of the Annapurna and Nilgiri ranges. This is a trek for experienced trekkers seeking a genuine wilderness challenge.','https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg?auto=compress&cs=tinysrgb&w=1600','16 Days','Expert','$2,500','Trek',32,
'[{"day":1,"title":"Arrive in Kathmandu","description":"Arrival and expedition briefing."},{"day":2,"title":"Drive to Beni","description":"Scenic drive from Kathmandu to Beni (830m)."},{"day":3,"title":"Beni to Dharapani","description":"Begin trekking through traditional villages."},{"day":4,"title":"Dharapani to Muri","description":"Walk through subtropical forests."},{"day":5,"title":"Muri to Boghara","description":"Enter alpine terrain."},{"day":6,"title":"Boghara to Dobang","description":"Trek through rhododendron forests."},{"day":7,"title":"Dobang to Sallaghari","description":"Approach the Dhaulagiri base camp area."},{"day":8,"title":"Sallaghari to Dhaulagiri BC","description":"Arrive at Dhaulagiri Base Camp (4,700m)."},{"day":9,"title":"Acclimatization at BC","description":"Rest and explore the base camp area."},{"day":10,"title":"Cross French Pass","description":"Cross French Pass (5,360m). Enter Hidden Valley."},{"day":11,"title":"Cross Dhampus Pass","description":"Cross Dhampus Pass (5,246m). Descend."},{"day":12,"title":"Trek to Marpha","description":"Descend to the apple-growing village of Marpha."},{"day":13,"title":"Explore Marpha","description":"Rest day in Marpha. Apple brandy tasting."},{"day":14,"title":"Drive to Pokhara","description":"Scenic drive from Jomsom to Pokhara."},{"day":15,"title":"Drive to Kathmandu","description":"Return to Kathmandu."},{"day":16,"title":"Departure","description":"Airport transfer."}]'::jsonb,
'["All ground transport","Hotel in Kathmandu","Camping equipment (tents, mattresses, kitchen)","All meals on trek","English-speaking guide","Cook and kitchen staff","Porter service","Dhaulagiri Conservation Area permit","TIMS card","Satellite phone"]'::jsonb,
'["International flights","Nepal visa","Travel insurance","Personal clothing and sleeping bag","Tips","Alcoholic drinks"]'::jsonb,
'["Trek around the world''s 7th highest mountain (8,167m)","Cross French Pass (5,360m) and Dhampus Pass (5,246m)","Explore the famous Hidden Valley","Camping expedition through Dhaulagiri Glacier","Views of Dhaulagiri, Annapurna, and Nilgiri ranges","One of Nepal''s most challenging wilderness treks"]'::jsonb),

-- RARA LAKE TREK (Far West)
('Rara Lake Trek','rara-lake-trek','A journey to Nepal''s largest lake in the remote far-west, surrounded by pristine forests and alpine meadows.','The Rara Lake Trek takes you to Rara Lake (2,990m), Nepal''s largest lake, located in the remote far-western region of the country. The lake is the centerpiece of Rara National Park, a pristine wilderness of pine, juniper, and rhododendron forests. The trek offers stunning views of the surrounding hills and distant Himalayan peaks including Saipal (7,031m). The region is home to diverse wildlife including musk deer, Himalayan black bears, and over 200 species of birds. The remote location means very few trekkers make it here, offering a truly off-the-beaten-path experience.','https://images.pexels.com/photos/2387871/pexels-photo-2387871.jpeg?auto=compress&cs=tinysrgb&w=1600','12 Days','Moderate','$1,400','Trek',33,
'[{"day":1,"title":"Arrive in Kathmandu","description":"Arrival and briefing."},{"day":2,"title":"Fly to Nepalgunj","description":"Domestic flight to Nepalgunj."},{"day":3,"title":"Fly to Jumla, Trek to Danphe Lagna","description":"Flight to Jumla. Begin trekking."},{"day":4,"title":"Danphe Lagna to Chautha","description":"Trek through pine forests and traditional villages."},{"day":5,"title":"Chautha to Dhotu","description":"Continue through beautiful landscapes."},{"day":6,"title":"Dhotu to Rara Lake","description":"Arrive at the stunning Rara Lake (2,990m)."},{"day":7,"title":"Explore Rara Lake","description":"Full day exploring the lake, national park, and surrounding hills."},{"day":8,"title":"Rara Lake to Sinja","description":"Trek to the historic Sinja Valley."},{"day":9,"title":"Explore Sinja","description":"Khas kingdom ruins and ancient inscriptions."},{"day":10,"title":"Sinja to Jumla","description":"Return trek to Jumla."},{"day":11,"title":"Fly to Kathmandu","description":"Return via Nepalgunj."},{"day":12,"title":"Departure","description":"Airport transfer."}]'::jsonb,
'["Airport transfers","All domestic flights","Hotel in Kathmandu","Teahouse accommodation","All meals on trek","English-speaking guide","Porter service","Rara National Park permit","TIMS card"]'::jsonb,
'["International flights","Nepal visa","Travel insurance","Personal gear","Tips","Alcoholic drinks"]'::jsonb,
'["Rara Lake — Nepal''s largest and most beautiful lake","Rara National Park — pristine wilderness","Remote far-west region — very few trekkers","Views of Saipal Himal (7,031m)","Historic Sinja Valley — ancient Khas kingdom","Over 200 species of birds and diverse wildlife"]'::jsonb),

-- GANESH HIMAL BASE CAMP TREK
('Ganesh Himal Base Camp Trek','ganesh-himal-base-camp','A cultural trek through the Ruby Valley to the base of sacred Ganesh Himal with stunning mountain panoramas.','The Ganesh Himal Base Camp Trek is a wonderful cultural trek through the Ruby Valley region, named for the precious stones found here. The trek offers spectacular views of the Ganesh Himal range, including Yangra (7,422m), the highest peak in the range. The trail passes through traditional Tamang and Buddhist villages, terraced fields, and rhododendron forests. You''ll visit hot springs at Tatopani, cross suspension bridges, and experience the rich cultural heritage of the region. This is a relatively new trekking route that remains uncrowded and authentic.','https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=1600','17 Days','Moderate','$1,550','Trek',34,
'[{"day":1,"title":"Arrive in Kathmandu","description":"Arrival and briefing."},{"day":2,"title":"Drive to Syabrubesi","description":"7-8 hour drive to Syabrubesi."},{"day":3,"title":"Syabrubesi to Gatlang","description":"Trek through Tamang villages to Gatlang."},{"day":4,"title":"Gatlang to Somdang","description":"Ascend through forests with mountain views."},{"day":5,"title":"Somdang to Pansing Kharka","description":"Trek to the base of Ganesh Himal."},{"day":6,"title":"Ganesh Himal Base Camp","description":"Hike to Ganesh Himal Base Camp (4,200m). Return to Pansing."},{"day":7,"title":"Pansing to Somdang","description":"Descend back through the valley."},{"day":8,"title":"Somdang to Tipling","description":"Trek through the Ruby Valley. Visit local gem mines."},{"day":9,"title":"Tipling to Shertung","description":"Continue through traditional villages."},{"day":10,"title":"Shertung to Jharlang","description":"Cross ridges with panoramic views."},{"day":11,"title":"Jharlang to Darkha","description":"Descend through forests and terraced fields."},{"day":12,"title":"Darkha to Malekhu","description":"Final trekking day to the road."},{"day":13,"title":"Drive to Kathmandu","description":"Return drive."}]'::jsonb,
'["Airport transfers","Private ground transport","Hotel in Kathmandu","Teahouse accommodation","All meals on trek","English-speaking guide","Porter service","National Park permit","TIMS card"]'::jsonb,
'["International flights","Nepal visa","Travel insurance","Personal gear","Tips","Alcoholic drinks"]'::jsonb,
'["Ganesh Himal views including Yangra (7,422m)","Ruby Valley — named for precious gemstones","Rich Tamang culture and Buddhist traditions","Hot springs and traditional villages","Relatively new route — few trekkers","Spectacular mountain panoramas"]'::jsonb)

) AS v(title, slug, description, long_description, image_url, duration, difficulty, price, category, sort_order, itinerary, includes, excludes, highlights)
WHERE NOT EXISTS (SELECT 1 FROM public.adventures WHERE slug = v.slug);


-- =====================================================
-- 2. NEW TOURS (category = 'Tour')
-- =====================================================
INSERT INTO public.adventures (title, slug, description, long_description, image_url, duration, difficulty, price, category, sort_order, itinerary, includes, excludes, highlights)
SELECT * FROM (VALUES

-- KATHMANDU VALLEY CULTURAL DAY TOUR
('Kathmandu Valley Cultural Day Tour','kathmandu-valley-day-tour','A guided tour of Kathmandu''s UNESCO World Heritage Sites including temples, stupas, and durbar squares.','Explore the cultural heart of Nepal on this comprehensive day tour of the Kathmandu Valley. Led by a licensed cultural guide, you''ll visit the most iconic UNESCO World Heritage Sites including Swayambhunath Stupa (Monkey Temple), Boudhanath Stupa (one of the largest in the world), Pashupatinath Temple (the holiest Hindu temple), and Kathmandu Durbar Square with its ancient palaces and the Living Goddess Kumari. This tour offers a deep dive into Nepal''s rich history, art, architecture, and living traditions.','https://images.pexels.com/photos/3389536/pexels-photo-3389536.jpeg?auto=compress&cs=tinysrgb&w=1600','1 Day','Easy','$89','Tour',50,
'[{"day":1,"title":"Kathmandu Valley Heritage Tour","description":"Hotel pickup at 8 AM. Visit Swayambhunath Stupa for panoramic valley views. Continue to Boudhanath Stupa, the largest stupa in Nepal. Visit Pashupatinath Temple on the Bagmati River. Afternoon: explore Kathmandu Durbar Square, visit the Living Goddess Kumari. Return to hotel by 4 PM."}]'::jsonb,
'["Hotel pickup and drop-off","Private air-conditioned vehicle","English-speaking cultural guide","All entry fees to heritage sites","Bottled water","Government taxes"]'::jsonb,
'["Lunch","Personal expenses","Tips for guide and driver"]'::jsonb,
'["Visit Swayambhunath Stupa (Monkey Temple)","Explore Boudhanath Stupa — one of largest in world","Visit the holy Pashupatinath Temple","See the Living Goddess Kumari at Durbar Square","Comprehensive cultural tour in one day"]'::jsonb),

-- CHISAPANI NAGARKOT HIKE
('Chisapani Nagarkot Hike','chisapani-nagarkot-hike','A short hiking adventure from Kathmandu through Shivapuri National Park to the sunrise viewpoints of Nagarkot.','This 3-day hiking tour is perfect for those who want a quick escape from Kathmandu into nature. Starting from Sundarijal, you''ll hike through Shivapuri National Park to Chisapani, a beautiful hill station with panoramic mountain views. On the second day, you''ll hike through forests and traditional villages to Nagarkot, famous for its sunrise views over the Himalayas. On a clear day, you can see Mount Everest from the viewpoint.','https://images.pexels.com/photos/2901209/pexels-photo-2901209.jpeg?auto=compress&cs=tinysrgb&w=1600','3 Days','Easy','$199','Tour',51,
'[{"day":1,"title":"Sundarijal to Chisapani","description":"Drive to Sundarijal. 4-5 hour hike through Shivapuri National Park to Chisapani (2,300m). Evening mountain views."},{"day":2,"title":"Chisapani to Nagarkot","description":"6-7 hour hike through forests and villages to Nagarkot (2,175m). Sunset over the Himalayas."},{"day":3,"title":"Nagarkot Sunrise & Return","description":"Early sunrise view from the Nagarkot tower. Drive back to Kathmandu."}]'::jsonb,
'["Hotel pickup and drop-off","English-speaking guide","Entry to Shivapuri National Park","2 nights teahouse accommodation","All meals on hike (2 breakfasts, 2 lunches, 2 dinners)"]'::jsonb,
'["Personal expenses","Travel insurance","Tips"]'::jsonb,
'["Hike through Shivapuri National Park","Panoramic Himalayan views from Chisapani and Nagarkot","Sunrise over Everest on clear days","Traditional Tamang villages along the trail","Quick escape from Kathmandu into nature"]'::jsonb),

-- LUXURY POKHARA TOUR
('Pokhara Tour','pokhara-tour','A relaxing 3-day tour of Pokhara with lakeside luxury, Himalayan views, and adventure activities.','Pokhara is Nepal''s adventure capital and most beautiful lakeside city. This 3-day luxury tour includes comfortable boutique accommodation, a guided city tour covering Devi''s Falls, Gupteshwor Cave, the International Mountain Museum, and the World Peace Pagoda. You''ll enjoy a sunrise trip to Sarangkot for panoramic Annapurna views, a boat ride on Phewa Lake, and optional adventure activities like paragliding or zip-lining. With private transport and expert guides, this is the perfect way to experience Pokhara in comfort.','https://images.pexels.com/photos/2356045/pexels-photo-2356045.jpeg?auto=compress&cs=tinysrgb&w=1600','3 Days','Easy','$349','Tour',52,
'[{"day":1,"title":"Drive to Pokhara & Lakeside Evening","description":"6-hour drive from Kathmandu or 25-minute flight. Check into lakeside hotel. Evening boat ride on Phewa Lake."},{"day":2,"title":"Sarangkot Sunrise & City Tour","description":"Pre-dawn trip to Sarangkot for sunrise. Visit Devi''s Falls, Gupteshwor Cave, and Mountain Museum."},{"day":3,"title":"World Peace Pagoda & Return","description":"Morning hike to World Peace Pagoda. View of the Annapurna range. Drive back to Kathmandu."}]'::jsonb,
'["Hotel pickup and drop-off","Round-trip tourist bus","2 nights Pokhara hotel (BB basis)","English-speaking guide","Sarangkot sunrise transfer","All entry fees"]'::jsonb,
'["Paragliding (optional)","Lunch and dinner","Personal expenses","Tips"]'::jsonb,
'["Phewa Lake views with Annapurna reflection","Sarangkot sunrise panorama","World Peace Pagoda hike","Explore Devi''s Falls and Gupteshwor Cave","Optional paragliding and adventure activities"]'::jsonb),

-- CHITWAN TOUR 3 DAYS
('Chitwan National Park Tour','chitwan-national-park-tour','A jungle safari adventure in Nepal''s premier national park with rhinos, tigers, and Tharu culture.','Chitwan National Park, a UNESCO World Heritage Site, is Nepal''s most famous wildlife reserve. This 3-day safari takes you deep into the jungle with expert naturalist guides. You''ll explore on elephant-back, in dugout canoes, and on foot. Spot one-horned rhinoceros, Bengal tigers, leopards, sloth bears, and over 500 species of birds. You''ll also visit a traditional Tharu village and enjoy a cultural dance performance. With comfortable jungle lodge accommodation, this is the perfect wildlife adventure.','https://images.pexels.com/photos/2433970/pexels-photo-2433970.jpeg?auto=compress&cs=tinysrgb&w=1600','3 Days','Easy','$399','Tour',53,
'[{"day":1,"title":"Drive to Chitwan & Tharu Village","description":"5-hour drive to Chitwan. Check into jungle lodge. Evening Tharu village walk and cultural dance."},{"day":2,"title":"Jungle Safari & Canoeing","description":"Elephant-back safari at dawn. Afternoon dugout canoe ride on the Rapti River. Nature walk. Crocodile spotting."},{"day":3,"title":"Birdwatching & Return","description":"Early birdwatching walk. Visit elephant breeding center. Drive back to Kathmandu."}]'::jsonb,
'["Hotel pickup and drop-off","Private round-trip transport","2 nights jungle lodge (full board)","English-speaking naturalist guide","Elephant-back safari","Dugout canoe ride","Chitwan National Park entry fee"]'::jsonb,
'["Travel insurance","Personal expenses","Tips","Alcoholic drinks"]'::jsonb,
'["Track one-horned rhinos on elephant-back","Search for the elusive Bengal tiger","Canoe alongside crocodiles","Tharu cultural dance performance","Over 500 species of birds"]'::jsonb)

) AS v(title, slug, description, long_description, image_url, duration, difficulty, price, category, sort_order, itinerary, includes, excludes, highlights)
WHERE NOT EXISTS (SELECT 1 FROM public.adventures WHERE slug = v.slug);


-- =====================================================
-- 3. NEW PLACES (Destinations not yet in the places table)
-- =====================================================
INSERT INTO public.places (name, description, image_url, type, sort_order)
SELECT * FROM (VALUES
-- Additional Langtang places
('Syabrubesi','A small mountain town at 1,460m serving as the gateway to the Langtang Valley and Tamang Heritage treks.','','trek',13),
('Thulo Syabru','A charming Tamang village perched on a ridge with stunning views of Langtang and Ganesh Himal.','','trek',14),
('Shin Gompa','A small monastery village known for its Buddhist heritage and famous yak cheese factory.','','trek',15),
('Gatlang','A beautiful Tamang village with traditional stone houses and panoramic mountain views.','','trek',16),
('Briddim','A culturally rich village offering authentic homestay experiences with Tamang families.','','trek',17),
('Thuman','A traditional Tamang village with Tibetan-influenced culture and ancient monasteries.','','trek',18),
('Tatopani','Famous for its natural hot springs (now dried up after 2015 earthquake), meaning "hot water" in Nepali.','','trek',19),

-- Additional Annapurna places
('Ghandruk','A picturesque Gurung village at 2,012m with stunning views of Annapurna South and Machhapuchhre.','','trek',20),
('Jhinu Danda','A village famous for its natural hot springs beside the Modi Khola River.','','trek',21),
('Deurali','A small settlement at 3,230m surrounded by dramatic cliffs and alpine scenery.','','trek',22),
('Bamboo','A forested settlement at 2,310m surrounded by dense bamboo groves.','','trek',23),
('Chomrong','A large Gurung village at 2,170m serving as the gateway to the Annapurna Sanctuary.','','trek',24),
('Khopra Ridge','A stunning ridge at 3,660m with unobstructed views of Dhaulagiri and Annapurna.','','trek',25),
('Muldai Viewpoint','A viewpoint at 3,900m offering spectacular sunrise views over the Annapurna and Dhaulagiri ranges.','','trek',26),
('Mardi Himal Base Camp','The base camp at 4,450m offering close-up views of Machhapuchhre and Mardi Himal.','','trek',27),

-- Additional Everest places
('Gokyo Lake','A series of six turquoise glacial lakes at 4,800m, designated as a Ramsar site.','','trek',28),
('Gokyo Ri','A viewpoint at 5,357m offering panoramic views of Everest, Lhotse, Makalu, and Cho Oyu.','','trek',29),
('Machhermo','A tranquil village at 3,870m on the Gokyo Lake trek route.','','trek',30),
('Dole','A small settlement at 3,680m on the way to Gokyo Lakes.','','trek',31),

-- Kanchenjunga places
('Kanchenjunga Base Camp','The base camp of the world''s 3rd highest mountain at 5,143m.','','trek',32),
('Phoksundo Lake','Nepal''s deepest lake at 3,611m, famous for its stunning turquoise color.','','trek',33),

-- Makalu places
('Makalu Base Camp','The base camp of the world''s 5th highest mountain at 4,870m.','','trek',34),
('Rara Lake','Nepal''s largest lake at 2,990m, located in the remote far-western region.','','trek',35),

-- Additional tour places
('Chisapani','A beautiful hill station at 2,300m offering panoramic Himalayan views.','','tour',15),
('Nagarkot','A scenic hill station at 2,175m famous for sunrise views over the Himalayas including Everest.','','tour',16)

) AS v(name, description, image_url, type, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM public.places WHERE name = v.name);


-- =====================================================
-- 4. UPDATE EXISTING ADVENTURES WITH MORE DETAIL
-- Enhanced itineraries for treks that had basic seed data
-- =====================================================
DO $$
BEGIN
  -- Update Langtang Valley Trek with enhanced data
  UPDATE public.adventures SET
    long_description = 'The Langtang Valley is often called the "Valley of Glaciers" and offers some of the most accessible high-altitude trekking in Nepal. Just a 7-hour drive from Kathmandu, the trail leads through dense forests of bamboo and rhododendron, past cascading waterfalls, to the stunning Langtang Valley. The region was devastated by the 2015 earthquake, but the recovery has been remarkable — new lodges, rebuilt monasteries, and the famous Langtang cheese factory are all operating again. Highlights include the serene Kyanjin Gompa monastery, views of Langtang Lirung (7,227m), and the challenging climb to Tserko Ri (4,985m) for panoramic views of 20+ Himalayan peaks.',
    highlights = '["Explore the beautiful Langtang Valley — the Valley of Glaciers","Trek through bamboo and rhododendron forests","Visit Kyanjin Gompa monastery and cheese factory","Climb Tserko Ri (4,985m) for panoramic views","No flight needed — 7 hour drive from Kathmandu","Remarkable post-earthquake recovery story"]'::jsonb,
    price = '$899',
    includes = '["Private ground transport Kathmandu-Syabrubesi","Teahouse accommodation","All meals on trek","English-speaking guide","Porter service","Langtang National Park permit","TIMS card","First aid kit"]'::jsonb
  WHERE slug = 'langtang-valley';

  -- Update Ghorepani Poon Hill Trek with enhanced data
  UPDATE public.adventures SET
    duration = '4 Days',
    price = '$599',
    includes = '["All ground transport","Teahouse accommodation","All meals on trek","English-speaking guide","Porter service","Annapurna Conservation Area permit","TIMS card","First aid kit"]'::jsonb
  WHERE slug = 'poon-hill-trek';

  -- Update Everst Base Camp Trek price
  UPDATE public.adventures SET
    price = '$1,459'
  WHERE slug = 'everest-base-camp';

  -- Update Manaslu Circuit Trek price
  UPDATE public.adventures SET
    price = '$1,699'
  WHERE slug = 'manaslu-circuit';

  -- Update Annapurna Circuit with enhanced details
  UPDATE public.adventures SET
    price = '$1,299'
  WHERE slug = 'annapurna-circuit';

END $$;
